# Generated by Django 5.2 on 2025-05-08 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcours', '0002_cours_filiere_promotion_feedback_cours_filiere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcours.cours')),
            ],
        ),
    ]
