# Generated by Django 5.2 on 2025-05-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcours', '0007_remove_feedback_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='description',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='aspects',
        ),
    ]
