# Generated by Django 5.2 on 2025-05-18 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcours', '0003_professeur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='professeur',
            options={'verbose_name': 'Professeur', 'verbose_name_plural': 'Professeurs'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
        migrations.AddField(
            model_name='cours',
            name='credit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cours',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='anonyme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='aspects',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='date_cours',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='partager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='appcours.professeur'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='annee_debut',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='annee_fin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='appcours.filiere'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='appcours.cours'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positif', 'Positif'), ('neutre', 'Neutre'), ('négatif', 'Négatif')], max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='cours',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='appcours.filiere'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='appcours.promotion'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='cours',
            field=models.ManyToManyField(related_name='professeurs', to='appcours.cours'),
        ),
    ]
