# Generated by Django 5.2 on 2025-05-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcours', '0005_remove_feedback_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='contact',
            field=models.BooleanField(default=False),
        ),
    ]
