# Generated by Django 5.2 on 2025-06-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcours', '0009_courseresource_modeevaluation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='theme_pred',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
