# Generated by Django 5.2 on 2025-05-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcours', '0004_alter_cours_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='contact',
        ),
    ]
