# Generated by Django 5.2 on 2025-05-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcours', '0006_feedback_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='contact',
        ),
    ]
